param:
  brightness: 
    0.0 
  gamma: 
    1.0 
  alpha: 
    1.0 
  angle: 
    0.0 
  scale: 
    1.0 
  shader: 
    userdata: 0000000000000000 
  contrast: 
    0.0 
  center: 
    x: 
      960.0 
    y: 
      540.0 
  color_key_range: 
    0.0 
  uv: 
    h: 
      0.99264705181122 
    y: 
      0.0 
    x: 
      0.0 
    w: 
      1.0 
  bounds: 
    h: 
      1080.0 
    y: 
      0.0 
    x: 
      0.0 
    w: 
      1920.0 
  cm: 
    1: 
      1: 
        0.37688400087506 
      2: 
        0.5217332072667 
      3: 
        0.10138279185824 
      4: 
        0.0 
    2: 
      1: 
        0.26579497284234 
      2: 
        0.63288934219889 
      3: 
        0.10131568495877 
      4: 
        0.0 
    3: 
      1: 
        0.26572786594287 
      2: 
        0.52183386761591 
      3: 
        0.21243826644123 
      4: 
        0.0 
    4: 
      1: 
        0.0 
      2: 
        0.0 
      3: 
        0.0 
      4: 
        1.0 
  color_key: 
    r: 
      0.0 
    a: 
      1.0 
    b: 
      0.0 
    g: 
      0.0 
  use_color_key: 
    false 
  color_key_alpha: 
    0.0 